### ISSUE TITLE
CRAN submission/release

### ISSUE THREAD

**Issue by bmcgough** [SESYNC-ci/rslurm#1]
My institution has an interest in using rslurm. We currently use EasyBuild to manage software builds. One of the reasons we use EasyBuild is to ensure installed software packages can be reproduced easily. This means that specific releases and versions are required (i.e.: we cannot build again a repo, only a release so future installs will contain identical code).

Do you have plans to submit rslurm to CRAN? I'm not sure what is involved in making an R library compliant with 'R CMD INSTALL <pkg>' but I would be willing to help out with that if it would be welcome.

**Comment by pmarchand1** [comment]
Hi @bmcgough, thanks for your message! Did you try the current version of the package? We will be adding some configuration options to make it more broadly usable, and your input would be greatly appreciated.

**Comment by bmcgough** [comment]
In following the instructions I am told to install devtools, and then use devtools::install_github to install rslurm. This appears to pull a zipball of master, not a release (I think 'devtools::install_github(ref=2.0) would pull release 2.0).

EasyBuild has a large number of basic building blocks, but currently lacks an R+devtools method for installation, so we cannot use rslurm at this time. Also, EasyBuild (for reproducibility) requires versions/releases.

Going forward, I can write an installer that uses R+devtools, but it would still only be able to use specific versions, and I don't see any releases for rslurm.

By far the easiest (for me, not you!) would be to have rslurm in CRAN. EasyBuild can 'easily' pull from CRAN during an R build.

**Comment by pmarchand1** [comment]
The new version of rslurm is now on CRAN (https://cran.r-project.org/web/packages/rslurm/index.html).

Please check the README file since the interface was changed for additional functionality and customization options.
