### ISSUE TITLE
Using rslurm with RefClasses

### ISSUE THREAD

**Issue by rcorty** [SESYNC-ci/rslurm#10]
I've documented an issue I'm having with rslurm and RefClasses on StackOverflow.

https://stackoverflow.com/questions/44681304/slurm-apply-a-refclass-method-from-within-a-refclass-method

I believe there may be something in the way that rslurm deals with namespaces in its processing (saving) of the `add_objects` argument that makes it hard to use rslurm with reference classes.

I would appreciate any clarification the rslurm development group might be able to offer on this issue.

**Comment by itcarroll** [comment]
Solution introduced in #13, and I added an answer to your stack question. As stated over there, I'll update when the next rslurm release hits CRAN with a working example.
