### ISSUE TITLE
Add option to add lines to .sh file?

### ISSUE THREAD

**Issue by kendonB** [SESYNC-ci/rslurm#15]
On my system, I need to add the line ``module load R`` before the call to Rscript for ``slurm_apply`` to work. Is it possible to do this from within ``rslurm``?

**Comment by rcorty** [comment]
Can you describe in a bit more detail what you mean by "before the call to Rscript"?

**Comment by kendonB** [comment]
It would write to the line right before the call to Rscript. As in change:

```
#!/bin/bash
#
#SBATCH --array=0-1
#SBATCH --job-name=test_apply
#SBATCH --output=slurm_%a.out

#SBATCH --account=landcare00063

#SBATCH --mem-per-cpu=1G

#SBATCH --time=1:00:00
/share/easybuild/RHEL6.3/sandybridge/software/R/3.4.0-gimkl-2017a/lib64/R/bin/Rscript --vanilla slurm_run.R
```
into:
```
#!/bin/bash
#
#SBATCH --array=0-1
#SBATCH --job-name=test_apply
#SBATCH --output=slurm_%a.out

#SBATCH --account=landcare00063

#SBATCH --mem-per-cpu=1G

#SBATCH --time=1:00:00
module load R
/share/easybuild/RHEL6.3/sandybridge/software/R/3.4.0-gimkl-2017a/lib64/R/bin/Rscript --vanilla slurm_run.R
```

**Comment by rcorty** [comment]
Add that line to inst/submit_sh.txt, so that it reads...

> #!/bin/bash
> #
> #SBATCH --array=0-{{{max_node}}}
> #SBATCH --job-name={{{jobname}}}
> #SBATCH --output=slurm_%a.out
> {{#flags}}
> #SBATCH --{{{name}}}
> {{/flags}}
> {{#options}}
> #SBATCH --{{{name}}}={{{value}}}
> {{/options}}
> module load R
> {{{rscript}}} --vanilla slurm_run.R

**Comment by rcorty** [comment]
May also need to make that change to inst/templates/slurm_run_single_R.txt

**Comment by kendonB** [comment]
Thanks! It's working now.

**Comment by qdread** [comment]
Closing this issue because slurm_apply and slurm_call now support custom templates (see pull request #47)
