### ISSUE TITLE
Ellipsis argument to slurm_apply()

### ISSUE THREAD

**Issue by wlandau-lilly** [SESYNC-ci/rslurm#16]
In other `apply()` family functions, I rely on `...` to pass arguments to my user-defined function. This is particularly important in places like [here](https://github.com/wlandau-lilly/drake/blob/master/R/future.R#L11) and [here](https://github.com/wlandau-lilly/drake/blob/master/R/mclapply.R#L9). I will need this functionality if I decide to implement a special `slurm_apply()` backend for [drake](https://github.com/SESYNC-ci/rslurm).

**Comment by rcorty** [comment]
The way to specify the arguments to `f` is through the `params` argument.

The documentation states:

params:  A data frame of parameter values to apply f to. Each column corresponds to a parameter of f (Note: names must match) and each row corresponds to a separate function call.

**Comment by wlandau-lilly** [comment]
I did see that, but it unfortunately does not fit my use case. I need to pass in a [large runtime configuration list](https://github.com/wlandau-lilly/drake/blob/master/R/mclapply.R#L10) that is very different from a data frame. Here, `config` is a list containing an environment, an [igraph object](https://github.com/igraph/igraph), a [storr cache](https://github.com/richfitz/storr), and a bunch of other unrelated objects. I guess I might try nesting it in a single-element `tibble`, but I would rather it not come to that, and I do not expect it to work with the rest of [drake](https://github.com/wlandau-lilly/drake)'s internals.

**Comment by rcorty** [comment]
Is the configuration list the same for all jobs?

**Comment by wlandau-lilly** [comment]
For each call to `slurm_lapply()`, yes.

**Comment by rcorty** [comment]
Have you looked into the ‘add_objects’ parameter?

**Comment by wlandau-lilly** [comment]
Sounds like that could work. The interface is not standard, but then again, neither is hpc.

**Comment by pmarchand1** [comment]
That's correct. We could have mirrored more closely the syntax of `mapply`/`mcmapply`, in which case `params` would be passed as individual vectors (rather than a data frame) and fixed arguments would be passed as `MoreArgs`. The current implementation is most convenient for functions that take a parameter vector and return a result vector, while allowing more flexible uses through `add_objects` and wrapper functions (as shown in the _Adding auxiliary data and functions_ section of the vignette).

**Comment by wlandau-lilly** [comment]
I was actually thinking of `apply()` itself, which accepts both `X` and `...`. But I am not too opinionated on this one.
