### ISSUE TITLE
Allow user to use different templates in slurm_apply

### ISSUE THREAD

**Issue by statquant** [SESYNC-ci/rslurm#19]
Hello, as per your vignette I found the templates located on `/templates`

```
.tmplib <- lapply(c('{{{pkg_list}}}'), 
                  library, character.only = TRUE, quietly = TRUE)
# some stuff
.rslurm_result <- do.call(parallel::mcMap, c(.rslurm_func,
    .rslurm_params[.rslurm_istart:.rslurm_iend, , drop = FALSE],
    mc.cores = {{{cpus_per_node}}}))
               
saveRDS(.rslurm_result, file = paste0('results_', .rslurm_id, '.RDS'))
```
Typically in my use case what ends up taking much time is reading back the RDS files generated (BTW: can I suggest using `saveRDS(...,compress=FALSE)` ), in cases where outputs are `data.table`s using `fst` to read/write would make massive difference.

Maybe as a FR it would be good to allow using user-defined templates as an option

**Comment by itcarroll** [comment]
Related to #15

**Comment by qdread** [comment]
Closing this issue because slurm_apply and slurm_call now support custom templates (see pull request #47)
