### ISSUE TITLE
problems specifying  a non-default cluster

### ISSUE THREAD

**Issue by dtenenba** [SESYNC-ci/rslurm#28]
I submitted a job on a non-default cluster (I added the following to my `slurm_apply()` call):

```R
slurm_options = list(clusters = "beagle")
```

But now, calls that are supposed to block by default until the job is done (such as `get_slurm_out()` instead fail and complain that the output files do not exist. 

Seems like the problem is that the `slurm_job` object (return value of `slurm_apply()`) does not keep track of the cluster that the job was started on, and it probably should. 

Everything works fine if I use the default cluster.

**Comment by itcarroll** [comment]
Thanks for reporting. It's difficult for me to recreate as I only have a single cluster available.

The problem is likely that the blocking mechanism runs on the default cluster, rather than "beagle". I will attempt a fix, but will have to ask you to test for me.

**Comment by itcarroll** [comment]
@dtenenba Perhaps not the quick fix I had hoped for. Before I proceed further, can you verify the problem by attempting your call to `slurm_apply` on the named cluster using `wait = FALSE`, then manually checking the Slurm queue for job completion, then proceeding with `get_slurm_out`?

Thank you.

**Comment by dtenenba** [comment]
Actually I think there's a better solution, which is just to set the environment variable `SLURM_CLUSTERS` to the desired value before starting R. Then every command will operate on the specified cluster and rslurm does not need to change. That is probably simpler and more elegant than any fix inside rslurm. I'm inclined to close this but I'll let you decide....

**Comment by itcarroll** [comment]
Have you tried it with SLURM_CLUSTERS set? It looks to me like `srun` does not respect it the way `sbatch` does, which would make the `srun` call fail to look for the job dependency on the right cluster. But if you have verified that the approach works, then feel free to close.

**Comment by dtenenba** [comment]
I will try it and let you know. Another option is we have a head node that is configured to use beagle as its default cluster (I assume srun as well) so that will work for folks at my institute, but may still  leave a problem for other users.

**Comment by dtenenba** [comment]
Yay, it works! 
Setting `SLURM_CLUSTERS` to my non-default cluster and then running a test job totally works. `print_job_status()` prints out the right value and `get_slurm_out()` blocks as expected until the job is done, and returns the correct results. So I'm not sure anything in rslurm needs to change, except maybe adding something about `SLURM_CLUSTERS` to the documentation in case anyone else comes along who wants to run it on a non-default cluster.

**Comment by dtenenba** [comment]
Thanks! Noticed a couple of typos in that commit (slrum instead of slurm).
