### ISSUE TITLE
compare to "future" package

### ISSUE THREAD

**Issue by itcarroll** [SESYNC-ci/rslurm#31]
https://github.com/HenrikBengtsson/future

The package says it includes Slurm backend, along with others, and serves as a unified front end for distributed computing. I need to investigate whether its functionality *could* supersede rslurm, and if so make some decisions about the future of rslurm.

**Comment by jamesdalg** [comment]
I don't think that future really can do the same thing as a slurm_apply. At least the documentation doesn't make it clear that you can. https://github.com/HenrikBengtsson/future/search?p=1&q=slurm&type=&utf8=%E2%9C%93
 It seems to be able to pull the number of cores from SLURM environmental variables, but not break a loop up into small jobs automatically, over multiple nodes. rslurm is actually pretty awesome and unique, I think. I'm a fan and will continue to use your package as a dependency for mine.
