### ISSUE TITLE
no slurm workload manager found 

### ISSUE THREAD

**Issue by behnam326** [SESYNC-ci/rslurm#32]
Hi,
I am trying to run the following example on a Linux cluster, when I register 2 nodes with 36 CPU per node.
test_func <- function(par_mu, par_sd) {
    samp <- rnorm(10^6, par_mu, par_sd)
    c(s_mu = mean(samp), s_sd = sd(samp))
}
pars <- data.frame(par_mu = 1:10,
                   par_sd = seq(0.1, 1, length.out = 10))
library(rslurm)
sjob <- slurm_apply(test_func, pars, jobname = 'test_apply',
                    nodes = 2, cpus_per_node = 20, submit = TRUE)

which I found in https://cran.r-project.org/web/packages/rslurm/vignettes/rslurm.html, as an example.
but I get the following error:
**sh: squeue: command not found
cannot submit; no slurm workload manager found submission scripts output in directory _rslurm-test_apply
warning massage: In system("squeue", ignore.stdout=TRUE): error in running command**

and i cannot find any result_*.RDS file in slurm sub folder.

Could you please help me to find my mistake?

Thanks

**Comment by msmorul** [comment]
from 'sh: squeue: command not found' it appears that the computer you're running rslurm from doesn't have the slurm utilities installed, or its not in the PATH set for R.

**Comment by behnam326** [comment]
we do not have slurm utility . is there any other package in R which could help me?

**Comment by itcarroll** [comment]
perhaps you can find what you are looking for in this documentation:
https://cran.r-project.org/web/views/HighPerformanceComputing.html

closing, since this is not an issue with rslurm.
