### ISSUE TITLE
.RDS files

### ISSUE THREAD

**Issue by jennysjaarda** [SESYNC-ci/rslurm#39]
The .RDS files are saved in the last specified directory within the defined function, is it possible to change them to save in the temporary _rslurm directory automatically? For now I have modified the start and end of my function as follow: 
myfunction <- function(x) 
{
slurm_dir <- getwd()
...
setwd(slurm_dir)
}

**Comment by itcarroll** [comment]
Which .RDS files do you mean?

When I run the "test_apply" job in the vignette, the "_rslurm_test_apply" folder does contain the .RDS files:

```
_rslurm_test_apply/
├── f.RDS
├── params.RDS
├── results_0.RDS
├── results_1.RDS
├── slurm_0.out
├── slurm_1.out
├── slurm_run.R
└── submit.sh
```

**Comment by jennysjaarda** [comment]
Hi,

The problem only occurs the directory is changed within the function
('f.RDS'), for example to read or write other files.

Jenny

**Comment by itcarroll** [comment]
Ah. Well, I'll add the functionality you request. But please consider that using `setwd` inside a script or function is not good practice. Fiery advice [here](https://www.tidyverse.org/articles/2017/12/workflow-vs-script/) and [here](https://swcarpentry.github.io/r-novice-inflammation/06-best-practices-R/#be-careful-when-using-setwd).

**Comment by jennysjaarda** [comment]
Ah I see, thanks for the tip. Normally I would not, but what would be the
best practice in the case of launching many slurm jobs where files are
being generated at each iteration?  For example, processing many files and
outputting results and parallelizing them over on the slurm cluster?

**Comment by qdread** [comment]
Hi @jennysjaarda I would recommend setting the file paths as strings and then using the function `file.path()` rather than changing the working directory within the function, following Ian's advice to avoid using `setwd()` within a function. For example, this function references different file paths without actually changing the working directory.

```
myfunction <- function(x) {
  input_path <- '/path/to/input/files'
  output_path <- '/where/to/save/files'
  my_csv <- read.csv(file.path(input_path, 'blah.csv'))

  ... do stuff ...

  write.csv(output, file.path(output_path, 'blah2.csv'))
}
```

Closing the issue now. Thanks for your input!
