### ISSUE TITLE
rslurm improvements

### ISSUE THREAD

**Issue by Tazovsky** [SESYNC-ci/rslurm#42]
Hi,
in my company we forked `rslurm` and developing additional features - i.e., we added support for executing slurm jobs on HPC from remote session i.e. local computer or docker container running on different host. Would you like us to contribute in your package?

**Comment by qdread** [comment]
Hi @Tazovsky , thanks so much for getting in contact with us and apologies for not responding sooner. We are currently in discussions about the "future" of rslurm and who will be in charge of maintaining the package. We would potentially be interested in your contributions, and we will get back in touch with you soon once we have figured out a path forward. Thanks again!

**Comment by qdread** [comment]
Hello again @Tazovsky I am following up because we are still potentially interested in your contributions to the package. We would welcome any pull requests you would like to contribute and will list you as a contributor if the contribution is significant.

**Comment by qdread** [comment]
No response . . . closing
