### ISSUE TITLE
Feature Request: Return the JobID in the slurm_job object.

### ISSUE THREAD

**Issue by grabear** [SESYNC-ci/rslurm#54]
Hi!

I was using rslurm, and I think it's a really cool project.  I do wish, however, that the returned object from `slurm_apply` and `slurm_map` contained more information about the submitted job.  Including the JobID.

If the JobID was parsed natively by your package, then it would be very useful in regards to job dependencies.

I would be very happy to create a Pull Request for this feature if you think it's worth putting in the package.

Anyways, thanks for such a useful package!

@grabear

**Comment by qdread** [comment]
Hi @grabear thanks very much for your input and for using rslurm. I believe this would be fairly straightforward to do by adding an additional argument to `slurm_job()` to add job ID to the object of class `slurm_job` that it outputs. Then you would pull the job ID within `slurm_apply()` and related functions, and submit it to `slurm_job()`. We would definitely appreciate it if you could create a pull request to implement that. Thanks again! -Quentin

**Comment by grabear** [comment]
@qdread thanks for the guidance!  I'll fork the repo and start making some changes.  I will refer back to this issue if I need anything.

**Comment by qdread** [comment]
Looks like we can close this issue now thanks to #55 ! And thanks to @grabear for the nice PR. Would you like to be listed as a contributor on the package (we typically do this for significant PRs)?

**Comment by grabear** [comment]
Hey, @qdread I would love to be added as a contributor!  Sorry for not responding sooner.  I have been using another account for work, so I tend to miss mentions.
