### ISSUE TITLE
Support mc.cores greater than number of physical cores

### ISSUE THREAD

**Issue by benfasoli** [SESYNC-ci/rslurm#56]
Hi all. Thanks for your continued hard work on rslurm!

I'd like the ability to specify a larger number of cores in `parallel::mcmapply(mc.cores = N)` than is used for the job submission script's `--cpus-per-task=M`. Some SLURM clusters allocate resources based on the physical core count and will raise an error if `M` exceeds the number of physical cores on available nodes.

It would be great to have the option to use different values for `M` and `N` so the number of forked processes can be managed independently from SLURM allocation instructions. This could be accomplished by adding a `threads_per_core` argument (following [sbatch flags](https://slurm.schedmd.com/mc_support.html)) to `slurm_apply` and `slurm_map` where `N = as.integer(threads_per_core * M)`. Or `M` and `N` could be specified independently with the default retaining the current behavior.

Let me know your thoughts. I'm happy to implement and submit a PR if it would be helpful.

**Comment by qdread** [comment]
Hi @benfasoli thanks for the suggestion! It would be great if you could submit a PR. I think your idea to retain current behavior as default is good, see #36 for additional discussion about backwards compatibility in the rslurm arguments that correspond to sbatch flags.
