### ISSUE TITLE
wait_for_job does not actually wait

### ISSUE THREAD

**Issue by PikalaxALT** [SESYNC-ci/rslurm#58]
I am using rslurm on an HPC and experiencing issues with retrieving the output from a submitted job. Essentially, the `wait_for_job` function uses an incorrect test: `test -z "$(squeue -hn ${JOB_NAME} 2>/dev/null)"` returns true if the job is not in the queue, and is a test for whether the job has finished... except you are using it as a test for whether it is still pending. I suggest the following change:

```diff
--- a/R/slurm_utils.R
+++ b/R/slurm_utils.R
@@ -48,7 +48,7 @@ wait_for_job <- function(slr_job) {
      queued <- system(
          paste('test -z "$(squeue -hn', slr_job$jobname, '2>/dev/null)"'),
          ignore.stderr = TRUE)
-     if (queued) {
+     if (!queued) {
          srun <- sprintf(paste('srun',
              '--nodes=1',
              '--time=0:1',
```

**Comment by qdread** [comment]
Thanks for noticing this! Is there any way you could submit a pull request?

**Comment by itcarroll** [comment]
I don't think the test is wrong, but I don't have a SLURM queue on hand to verify. I'd just point out that:
```
> system('test -z "xyz"') == TRUE
[1] TRUE
```
I think `queued` is `TRUE` if the job is in the queue.

**Comment by qdread** [comment]
I've verified this on the Slurm queue. If `JOB_NAME` appears in the output of `squeue -hn ${JOB_NAME}`, that means that the job is either currently running or waiting to run. Therefore `queued` is `TRUE` if the job is in the queue. So based on that I think @itcarroll is correct and no change is needed.

**Comment by qdread** [comment]
Hi @PikalaxALT I believe your issue was because of an incompatibility between `rslurm 0.5.0` and newer versions of `Slurm`. Hopefully the changes we made for `rslurm 0.6.0` resolve this problem!
