### ISSUE TITLE
Question: Issue rslurm jobs from outside slurm compute nodes?

### ISSUE THREAD

**Issue by thistleknot** [SESYNC-ci/rslurm#62]
I love and I mean love rslurm.

It doesn't have load balancing like clusterApplyLB but I presume mcpreschedule=FALSE handles that

I have 4 compute nodes (served over proxmox vm's).  They are working beautifully.

Each compute node runs R/Rstudio.  The R studio bit is causing the node that I actually run Rstudio on to use more ram than the other nodes.  Not really an issue as I can increase the RAM, but it does ruin the symmetry I had hoped to maintain across my compute nodes.

Is there a way to issue rslurm jobs to slurm compute nodes from rstudio outside of the slurm compute nodes?

I'm not really sure how to do that.  This might not be an rslurm question, but simply a slurm question.

For example.  I cannot issue srun from my slurm controller, but only from compute nodes.  This limitation has me issuing my rslurm jobs from the compute nodes (which means I need to run rstudio on a compute node).

**Comment by msmorul** [comment]
The only requirement for submitting slurm jobs are that the nodes be part of the slurm cluster. nodes can be part of a cluster, but not receive jobs or be considered 'compute' nodes. This is a pretty common configuration for most HPC systems in which you have a bastion host that is publicly accessible via ssh and folks run sbatch and stage data through. Originally at sesync (not sure how they have it setup now) rstudio server itself was part of the slum cluster, but only able to submit jobs to the cluster.

**Comment by qdread** [comment]
Thanks @msmorul for commenting! Yes, I believe this is a situation where different HPC systems are configured in different ways. For example, at the HPC system at Michigan State where I used to work, jobs could only be submitted from compute nodes, not the front-end node. But at SESYNC there is no such restriction and jobs could be submitted from any node. This is probably something you'd have to discuss with your system administrator.

**Comment by thistleknot** [comment]
> The only requirement for submitting slurm jobs are that the nodes be part of the slurm cluster. nodes can be part of a cluster, but not receive jobs or be considered 'compute' nodes. This is a pretty common configuration for most HPC systems in which you have a bastion host that is publicly accessible via ssh and folks run sbatch and stage data through. Originally at sesync (not sure how they have it setup now) rstudio server itself was part of the slum cluster, but only able to submit jobs to the cluster.

I thought about that.  In slurm.conf I can specify which nodes are the compute nodes.  I figure I install and setup another node w slurmd (heck, maybe I can have my controller be it) but not have it be one of the compute nodes specified in slurm.conf

**Comment by thistleknot** [comment]
apparently the slurm controller CAN issue jobs without slurmd running.

whoops.

This question is answered.

**Comment by qdread** [comment]
Thanks for using rslurm!
