### ISSUE TITLE
`slurm_map` not exported on CRAN version

### ISSUE THREAD

**Issue by aloy** [SESYNC-ci/rslurm#63]
I was wondering when the CRAN version will export the function `slurm_map()`. IT likes to use the CRAN version and not the GitHub version at work, so I am curious. Thanks!

**Comment by qdread** [comment]
Thanks for your interest! I'm glad you reminded us we are a little overdue to get another release submitted to CRAN. 😊  Hopefully we can get another version submitted fairly soon, though I can't say for sure when that will happen.

**Comment by qdread** [comment]
Hey just got the new release out so now you can use `slurm_map()` on CRAN! 🥂
