### ISSUE TITLE
Jobs waiting in queue will produce an error in get_job_status

### ISSUE THREAD

**Issue by LizaDarrous** [SESYNC-ci/rslurm#72]
If I've launched jobs using rslurm and they're stuck in queue due to resources and haven't yet launched, the first part of the get_job_status will return a FALSE in 'completed' status, but the next part that collects the log files will produce an error specifically for the following snippet:
 ` logs <- vapply(out_files, 
                   function(outf) paste(readLines(outf), collapse = "\n"),
                   "")`
, with Error message
`Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file '_rslurm_PABMI_optim/slurm_0.out': No such file or directory`

Is it possible to remove the log file retrieval, or only print it if $completed == TRUE?

**Comment by qdread** [comment]
Thanks for bringing this to our attention. It seems like a reasonably easy thing to fix so I should be able to resolve this issue for you. In the meantime, if you have a potential solution, please feel free to submit a pull request! 😁

**Comment by qdread** [comment]
I think commit 53b5d40 resolves this. Now `get_job_status` first checks which log files exist, then reads only those files. If none exist yet, the `logs` object will be empty in the output. I'm closing this issue but please let us know if there is still a problem.

**Comment by LizaDarrous** [comment]
Thank you for the quick update!
