### ISSUE TITLE
Allow for slurm_options without arguments

### ISSUE THREAD

**Issue by bric-afisher** [SESYNC-ci/rslurm#82]
Thank you so much for creating this package! It's immensely helpful!!

Would it be possible to expand `slurm_options` to allow for things like `--wait`, that do not have a value or argument associated with them? I've tried to do just

```r
sjob <- slurm_map(
  x = myx,
  f = myf,
  slurm_options = list('wait')
)
```

but this produces the error `sbatch: option '--=wait' is ambiguous...`. 

Alternatively, setting `slurm_options = list('wait'='')` produces the error `sbatch: option '--wait' doesn't allow an argument`.

Is there a way to use the `sbatch --wait` option?

**Comment by qdread** [comment]
Try `slurm_options = list(wait = TRUE)`.

**Comment by bric-afisher** [comment]
That works perfectly! Thank you!
