### ISSUE TITLE
Line endings

### ISSUE THREAD

**Issue by mhesselbarth** [SESYNC-ci/rslurm#84]
I am currently running into the following error on the HPC. I know how to solve this issue "by hand", I was wondering if there is any chance to do this internally within the rslurm packages.

```
sbatch: error: Batch script contains DOS line breaks (\r\n)
sbatch: error: instead of expected UNIX line breaks (\n).
```

My lokal session info:
```
> sessionInfo()
R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default


locale:
[1] LC_COLLATE=en_US.UTF-8  LC_CTYPE=en_US.UTF-8    LC_MONETARY=en_US.UTF-8 LC_NUMERIC=C           
[5] LC_TIME=en_US.UTF-8    

time zone: Europe/Vienna
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rslurm_0.6.2

loaded via a namespace (and not attached):
[1] compiler_4.3.1 parallel_4.3.1 tools_4.3.1    whisker_0.4.1 
```

**Comment by qdread** [comment]
No unfortunately rslurm does not internally check for Unix line breaks. There is a utility `dos2unix` which you can install that will convert DOS line breaks to Unix line breaks. Or this one-liner will work:

```
sed -i.bak "s/\r$//" myjob.sh
```

Is this occurring when you use rslurm defaults or when you use a custom batch script?

**Comment by mhesselbarth** [comment]
I am using the defaults and this is my function call: 

```
sjob <- slurm_apply(f = fx,  params = par_df,  y = 10,  
                                 jobname = 'my_first_test', nodes = nrow(par_df), cpus_per_node = 1,
                                 rscript_path = "$HOME/.spack/install/haswell/gcc-9.3.0/r-4.0.3-5z5kqf/rlib/R/bin/Rscript",  
                                 slurm_options = list("time" = "00:05:00",  "mem-per-cpu" = "1G"),
                                 submit = FALSE)
```

I am copy the folder to the HPC and submit there.

**Comment by mhesselbarth** [comment]
> sed -i.bak "s/\r$//" myjob.sh

This seems to be the easiest way and works pretty well. Thanks for the help 👍

**Comment by qdread** [comment]
It actually may be desirable to add this functionality to rslurm. I will make a new issue and address when I have time. Thanks for bringing it to our attention!
